<a href="https://colab.research.google.com/github/chavattecedric-cloud/public/blob/main/Copie_de_%5BS%5DDojo_API_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Durée :**

- Matinée (  3 h)

**Problématique et objectifs :**

Comment récupérer et exploiter les données sur la qualité de l'air pour identifier les zones à risque en France ?

Pour cela, il faudra :

- Récupérer les indicateurs de qualité de l'air.
- Analyser les données pour identifier les zones géographiques à risque en France.

Dans ce Dojo, nous allons nous intéresser dans une première partie à l'extraction et le nettoyage de la donnée.

Dans le prochain Dojo, nous aurons à Explorer la donnée et indentifier les zones à risques en France

**Contexte**

Tout au long de ce challenge, nous allons utiliser l'API `World Air Quality - OpenAQ`, qui permet d'obtenir des informations sur la qualité de l'air. Vous pouvez commencer à l'explorer rapidement  

- [lien vers l'api](https://public.opendatasoft.com/explore/dataset/openaq/information/?disjunctive.measurements_parameter&disjunctive.location&disjunctive.city&sort=measurements_lastupdated)


Nous allons nous concentrer sur les données de la `France`, pour l'année `2025`

Les polluants à étudier sont :


- **O3 (Ozone)** : Gaz qui peut être nocif pour la santé lorsqu'il est présent en grande quantité au niveau du sol. L'ozone est un composant majeur du smog.
- **NO2 (Dioxyde d'azote)** : Gaz irritant pour les voies respiratoires, produit par la combustion des carburants fossiles.

- **PM10** : Particules de diamètre inférieur à 10 microns. Ces particules peuvent pénétrer les voies respiratoires et causer des problèmes de santé.
- **PM2.5** : Particules fines de diamètre inférieur à 2,5 microns. Elles sont particulièrement dangereuses car elles peuvent pénétrer profondément dans les poumons et même entrer dans la circulation sanguine.

# packages

In [1]:
# Pour faire des requêtes web (API)
import requests
# Pour la manipulation des dataframe
import pandas as pd
# Pour afficher joliment les json
from pprint import pprint
# Pour afficher des barres de progression dans une boucle
from tqdm import tqdm

# gestion des temps
import time

## Q1 : Récupération des données initiales

Votre première tâche est d'identifier l'URL de base de l'API permettant de récupérer les données de qualité de l'air, en vous aidant notamment de cette [page d'exploration OpenDataSoft](https://public.opendatasoft.com/explore/dataset/openaq/api/?sort=measurements_lastupdated).

Lorsque vous essaierez les différentes requêtes, vous verrez l'**URL mise à jour en bas de page**, ce qui vous aidera grandement.

La construction de l'url doit tenir compte des filtres suivants :

-   **country** : `FR` (France)
-   **date** : Ciblez l'année `2025`.
-   **polluants** : Les polluants cibles sont `['pm10', 'pm2.5', 'o3', 'no2']`.
-   **offset** : Définir à `0` pour obtenir la première "page" de résultats.
-   **limit** : Fixer le nombre maximum d'enregistrements par page à `50`.



---

Une fois que vous avez identifié l'URL de base et compris comment appliquer les filtres pour cette API , créez une fonction Python qui :


1.  Effectue une requête `GET` vers l'url définit de API en utilisant la bibliothèque `requests`.
2.  Vérifie si la requête a réussi (code statut 200).

3.  Retourne les données sous forme de JSON.

In [11]:
def api ():
  link = 'https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/openaq/records?limit=50&offset=0&refine=country_name_en%3A%22France%22&refine=measurements_lastupdated%3A%222025%22&refine=measurements_parameter%3A%22PM10%22&refine=measurements_parameter%3A%22PM2.5%22&refine=measurements_parameter%3A%22O3%22&refine=measurements_parameter%3A%22NO2%22'
  r = requests.get(link)
  if r.status_code == 200:
    data=r.json()
  return data

In [18]:
api()

{'total_count': 1191,
 'results': [{'country': 'FR',
   'city': 'OUTREAU',
   'location': 'Outreau',
   'coordinates': {'lon': 1.5765700000004375, 'lat': 50.69434999996249},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 67.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'SAINT-LOUIS',
   'location': 'Sarda Garriga',
   'coordinates': {'lon': 55.40306500012004, 'lat': -21.277074999934275},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 8.6,
   'measurements_lastupdated': '2025-01-21T06:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'GRANDE-SYNTHE',
   'location': 'Grande-synthe',
   'coordinates': {'lon': 2.302149999732888, 'lat': 51.02446000023847},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 24.8,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'DOLE',
   'location': 'Dole centre',
   'coordinates': {'lon': 5.4963890001639415, 'lat': 47.09672000003368},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 56.8,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'SAINT-ESTÈVE',
   'location': 'Perpignan St Esteve',
   'coordinates': {'lon': 2.83987999987422, 'lat': 42.71979999993561},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 55.3,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'NÎMES',
   'location': 'Nimes Planas',
   'coordinates': {'lon': 4.361989999592602, 'lat': 43.82990000029993},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 30.1,
   'measurements_lastupdated': '2025-01-27T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'IFS',
   'location': 'IFS Caen sud',
   'coordinates': {'lon': -0.35277799979276353, 'lat': 49.15167000014074},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 51.5,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'VESOUL',
   'location': 'Vesoul Pres Caillet',
   'coordinates': {'lon': 6.157641999754988, 'lat': 47.620020000051525},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 11.1,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CAEN',
   'location': 'Caen Chemin-Vert',
   'coordinates': {'lon': -0.3911110003265554, 'lat': 49.19222000003276},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 12.9,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CHAMPFORGEUIL',
   'location': 'Champforgueil',
   'coordinates': {'lon': 4.835082999971133, 'lat': 46.821056000156496},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 5.1,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CROLLES',
   'location': 'Gresivaudan Periurb',
   'coordinates': {'lon': 5.882199999603001, 'lat': 45.27969999987679},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 12.2,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'ANNECY',
   'location': 'NOVEL',
   'coordinates': {'lon': 6.135556000416689, 'lat': 45.91694300011561},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 3.1,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'LE TAMPON',
   'location': 'Station Bourg-Murat',
   'coordinates': {'lon': 55.58262000039505, 'lat': -21.204814999614452},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 1.7,
   'measurements_lastupdated': '2025-01-31T05:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BOURGES',
   'location': 'Leblanc',
   'coordinates': {'lon': 2.405332999566499, 'lat': 47.08278000000045},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 1.9,
   'measurements_lastupdated': '2025-01-28T01:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BOURGES',
   'location': 'Bourges-Baffier',
   'coordinates': {'lon': 2.407182999944083, 'lat': 47.07504299984002},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 21.7,
   'measurements_lastupdated': '2025-01-21T00:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'NICE',
   'location': 'NICE ARSON',
   'coordinates': {'lon': 7.286255999915251, 'lat': 43.702076000066626},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 33.9,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'MONTGERON',
   'location': 'MONTGERON',
   'coordinates': {'lon': 2.4572000002045304, 'lat': 48.706699999881124},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 0.3,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'FRÉJUS',
   'location': 'ESTEREL',
   'coordinates': {'lon': 6.7683900000872725, 'lat': 43.437873999889575},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 47.9,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BOUGUENAIS',
   'location': 'LES COUETS',
   'coordinates': {'lon': -1.591497199973763, 'lat': 47.18591999976648},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 19.3,
   'measurements_lastupdated': '2025-01-28T06:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'ANGERS',
   'location': 'ROI RENE',
   'coordinates': {'lon': -0.5546860002680776, 'lat': 47.46699000003936},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 42.3,
   'measurements_lastupdated': '2025-01-31T02:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'MARMANDE',
   'location': 'MARMANDE',
   'coordinates': {'lon': 0.14269499965193722, 'lat': 44.508779999705844},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 13.9,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'GUÉRET',
   'location': 'GUERET - Nicolas',
   'coordinates': {'lon': 1.8730239997881732, 'lat': 46.17362000006616},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 15.3,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'AIRVAULT',
   'location': 'AIRVAULT - Stade Laillé',
   'coordinates': {'lon': -0.13563399987194635, 'lat': 46.82379500017337},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 9.4,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'NIORT',
   'location': 'Niort Venise',
   'coordinates': {'lon': -0.4828609996053624, 'lat': 46.320026000248056},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 1.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'MONT-DE-MARSAN',
   'location': 'MONT-DE-MARSAN - MIDOUZE',
   'coordinates': {'lon': -0.507028000198241, 'lat': 43.88897299969277},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 5.0,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'KOUROU',
   'location': 'Kourou Gaston Monnerville Brady',
   'coordinates': {'lon': -52.64649000042069, 'lat': 5.164247999692364},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 65.2,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'KOUROU',
   'location': 'Kourou Gaston Monnerville Brady',
   'coordinates': {'lon': -52.64649000042069, 'lat': 5.164247999692364},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 25.6,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'PEYRUSSE-VIEILLE',
   'location': 'PEYRUSSE',
   'coordinates': {'lon': 0.17906900002820078, 'lat': 43.62869999973773},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 7.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'MANOSQUE',
   'location': 'MANOSQUE',
   'coordinates': {'lon': 5.786131000151143, 'lat': 43.835784999886975},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 16.8,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'AVIGNON',
   'location': 'Avignon Rocade De Gaulle',
   'coordinates': {'lon': 4.826874999795343, 'lat': 43.931400000209464},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 16.4,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'LA PENNE-SUR-HUVEAUNE',
   'location': 'VALLEE HUVEAUNE',
   'coordinates': {'lon': 5.5113839995850205, 'lat': 43.28333999977458},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 28.6,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'RIOM',
   'location': 'Riom Périurbaine',
   'coordinates': {'lon': 3.122253999934768, 'lat': 45.896739999896965},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 9.6,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'VILLEFRANCHE-SUR-SAÔNE',
   'location': 'Villefranche Centre',
   'coordinates': {'lon': 4.715565999801707, 'lat': 45.99011200007032},
   'measurements_parameter': 'PM2.5',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 8.4,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'LORIENT',
   'location': 'Lorient B. Bissonnet',
   'coordinates': {'lon': -3.3950099996579963, 'lat': 47.74249999990309},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 2.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'DUNKERQUE',
   'location': 'St Pol mer - cheminots',
   'coordinates': {'lon': 2.332357999931567, 'lat': 51.03275999983689},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 38.5,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'LAVAL',
   'location': 'LAVAL-La Paix',
   'coordinates': {'lon': -0.7670800000206227, 'lat': 48.071059999775585},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 26.6,
   'measurements_lastupdated': '2025-01-31T02:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'PARAY-LE-FRÉSIL',
   'location': 'Paray le Fresil',
   'coordinates': {'lon': 3.600667000393966, 'lat': 46.652667999845924},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 43.3,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'GRAND-COURONNE',
   'location': 'Gd Couronne Mairie',
   'coordinates': {'lon': 1.0078530004089747, 'lat': 49.358214999834985},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 20.1,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'SAINT-DIZIER',
   'location': 'St DIZIER L. Michel',
   'coordinates': {'lon': 4.966110999614851, 'lat': 48.64583599977771},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 15.8,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'SAINT-DIZIER',
   'location': 'St DIZIER L. Michel',
   'coordinates': {'lon': 4.966110999614851, 'lat': 48.64583599977771},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 51.9,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CORNEILHAN',
   'location': 'Biterrois-Narbonnais',
   'coordinates': {'lon': 3.1887800004332134, 'lat': 43.40680000014959},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 37.3,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CREIL',
   'location': 'Faiencerie Creil',
   'coordinates': {'lon': 2.474397000355699, 'lat': 49.25955200025786},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 23.4,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'VESOUL',
   'location': 'Vesoul Pres Caillet',
   'coordinates': {'lon': 6.157641999754988, 'lat': 47.620020000051525},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 9.3,
   'measurements_lastupdated': '2025-01-30T12:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BÉTHUNE',
   'location': 'Bethune Stade',
   'coordinates': {'lon': 2.635691999749327, 'lat': 50.535384999862295},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 4.0,
   'measurements_lastupdated': '2025-01-28T02:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BOURGOIN-JALLIEU',
   'location': 'Bourgoin-Jallieu',
   'coordinates': {'lon': 5.270872000210893, 'lat': 45.60821999991515},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 6.7,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'CAEN',
   'location': 'Caen Chemin-Vert',
   'coordinates': {'lon': -0.3911110003265554, 'lat': 49.19222000003276},
   'measurements_parameter': 'PM10',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 8.7,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'LIEUDIEU',
   'location': 'Plateau de Bonnevaux',
   'coordinates': {'lon': 5.1810810001913, 'lat': 45.46089999997043},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 47.4,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'METZ',
   'location': 'Metz-Centre',
   'coordinates': {'lon': 6.180832999656292, 'lat': 49.11944200020039},
   'measurements_parameter': 'NO2',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 34.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'BRUNSTATT-DIDENHEIM',
   'location': 'Mulhouse Est',
   'coordinates': {'lon': 7.341603000302108, 'lat': 47.72310600007671},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 51.0,
   'measurements_lastupdated': '2025-01-31T08:00:00+00:00',
   'country_name_en': 'France'},
  {'country': 'FR',
   'city': 'PASSY',
   'location': 'PASSY',
   'coordinates': {'lon': 6.713610999962987, 'lat': 45.923609999787196},
   'measurements_parameter': 'O3',
   'measurements_sourcename': 'eea',
   'measurements_unit': 'µg/m³',
   'measurements_value': 0.4,
   'measurements_lastupdated': '2025-01-31T07:00:00+00:00',
   'country_name_en': 'France'}]}

In [21]:
data=api()

## Q2 : Transformation en DataFrame

Votre prochaine tâche est de créer une fonction permettant de transformer le dictionnaire JSON obtenu de la requête API (que vous avez implémentée en Q1) en un DataFrame pandas.

In [22]:
def json_df (data):
  return pd.json_normalize(data,record_path='results')

In [23]:
json_df(data)

,country,city,location,measurements_parameter,measurements_sourcename,measurements_unit,measurements_value,measurements_lastupdated,country_name_en,coordinates.lon,coordinates.lat
0,FR,OUTREAU,Outreau,O3,eea,µg/m³,67.0,2025-01-31T08:00:00+00:00,France,1.576570,50.694350
1,FR,SAINT-LOUIS,Sarda Garriga,NO2,eea,µg/m³,8.6,2025-01-21T06:00:00+00:00,France,55.403065,-21.277075
2,FR,GRANDE-SYNTHE,Grande-synthe,NO2,eea,µg/m³,24.8,2025-01-31T08:00:00+00:00,France,2.302150,51.024460
3,FR,DOLE,Dole centre,O3,eea,µg/m³,56.8,2025-01-31T07:00:00+00:00,France,5.496389,47.096720
4,FR,SAINT-ESTÈVE,Perpignan St Esteve,O3,eea,µg/m³,55.3,2025-01-30T12:00:00+00:00,France,2.839880,42.719800
5,FR,NÎMES,Nimes Planas,PM10,eea,µg/m³,30.1,2025-01-27T08:00:00+00:00,France,4.361990,43.829900
6,FR,IFS,IFS Caen sud,O3,eea,µg/m³,51.5,2025-01-31T08:00:00+00:00,France,-0.352778,49.151670
7,FR,VESOUL,Vesoul Pres Caillet,PM2.5,eea,µg/m³,11.1,2025-01-30T12:00:00+00:00,France,6.157642,47.620020
8,FR,CAEN,Caen Chemin-Vert,NO2,eea,µg/m³,12.9,2025-01-31T08:00:00+00:00,France,-0.391111,49.192220
9,FR,CHAMPFORGEUIL,Champforgueil,PM2.5,eea,µg/m³,5.1,2025-01-30T12:00:00+00:00,France,4.835083,46.821056
10,FR,CROLLES,Gresivaudan Periurb,PM2.5,eea,µg/m³,12.2,2025-01-31T08:00:00+00:00,France,5.882200,45.279700
11,FR,ANNECY,NOVEL,O3,eea,µg/m³,3.1,2025-01-31T07:00:00+00:00,France,6.135556,45.916943
12,FR,LE TAMPON,Station Bourg-Murat,NO2,eea,µg/m³,1.7,2025-01-31T05:00:00+00:00,France,55.582620,-21.204815
13,FR,BOURGES,Leblanc,NO2,eea,µg/m³,1.9,2025-01-28T01:00:00+00:00,France,2.405333,47.082780
14,FR,BOURGES,Bourges-Baffier,NO2,eea,µg/m³,21.7,2025-01-21T00:00:00+00:00,France,2.407183,47.075043
15,FR,NICE,NICE ARSON,NO2,eea,µg/m³,33.9,2025-01-31T08:00:00+00:00,France,7.286256,43.702076
16,FR,MONTGERON,MONTGERON,O3,eea,µg/m³,0.3,2025-01-31T08:00:00+00:00,France,2.457200,48.706700
17,FR,FRÉJUS,ESTEREL,O3,eea,µg/m³,47.9,2025-01-31T08:00:00+00:00,France,6.768390,43.437874
18,FR,BOUGUENAIS,LES COUETS,PM10,eea,µg/m³,19.3,2025-01-28T06:00:00+00:00,France,-1.591497,47.185920
19,FR,ANGERS,ROI RENE,NO2,eea,µg/m³,42.3,2025-01-31T02:00:00+00:00,France,-0.554686,47.466990
20,FR,MARMANDE,MARMANDE,NO2,eea,µg/m³,13.9,2025-01-31T07:00:00+00:00,France,0.142695,44.508780
21,FR,GUÉRET,GUERET - Nicolas,PM10,eea,µg/m³,15.3,2025-01-30T12:00:00+00:00,France,1.873024,46.173620
22,FR,AIRVAULT,AIRVAULT - Stade Laillé,NO2,eea,µg/m³,9.4,2025-01-31T08:00:00+00:00,France,-0.135634,46.823795
23,FR,NIORT,Niort Venise,O3,eea,µg/m³,1.0,2025-01-31T08:00:00+00:00,France,-0.482861,46.320026
24,FR,MONT-DE-MARSAN,MONT-DE-MARSAN - MIDOUZE,PM2.5,eea,µg/m³,5.0,2025-01-31T07:00:00+00:00,France,-0.507028,43.888973
25,FR,KOUROU,Kourou Gaston Monnerville Brady,O3,eea,µg/m³,65.2,2025-01-31T07:00:00+00:00,France,-52.646490,5.164248
26,FR,KOUROU,Kourou Gaston Monnerville Brady,PM2.5,eea,µg/m³,25.6,2025-01-31T07:00:00+00:00,France,-52.646490,5.164248
27,FR,PEYRUSSE-VIEILLE,PEYRUSSE,PM10,eea,µg/m³,7.0,2025-01-31T08:00:00+00:00,France,0.179069,43.628700
28,FR,MANOSQUE,MANOSQUE,O3,eea,µg/m³,16.8,2025-01-31T08:00:00+00:00,France,5.786131,43.835785
29,FR,AVIGNON,Avignon Rocade De Gaulle,PM10,eea,µg/m³,16.4,2025-01-30T12:00:00+00:00,France,4.826875,43.931400
30,FR,LA PENNE-SUR-HUVEAUNE,VALLEE HUVEAUNE,O3,eea,µg/m³,28.6,2025-01-31T08:00:00+00:00,France,5.511384,43.283340
31,FR,RIOM,Riom Périurbaine,PM10,eea,µg/m³,9.6,2025-01-31T08:00:00+00:00,France,3.122254,45.896740
32,FR,VILLEFRANCHE-SUR-SAÔNE,Villefranche Centre,PM2.5,eea,µg/m³,8.4,2025-01-31T08:00:00+00:00,France,4.715566,45.990112
33,FR,LORIENT,Lorient B. Bissonnet,O3,eea,µg/m³,2.0,2025-01-31T08:00:00+00:00,France,-3.395010,47.742500
34,FR,DUNKERQUE,St Pol mer - cheminots,O3,eea,µg/m³,38.5,2025-01-31T08:00:00+00:00,France,2.332358,51.032760
35,FR,LAVAL,LAVAL-La Paix,NO2,eea,µg/m³,26.6,2025-01-31T02:00:00+00:00,France,-0.767080,48.071060
36,FR,PARAY-LE-FRÉSIL,Paray le Fresil,O3,eea,µg/m³,43.3,2025-01-31T08:00:00+00:00,France,3.600667,46.652668
37,FR,GRAND-COURONNE,Gd Couronne Mairie,PM10,eea,µg/m³,20.1,2025-01-31T08:00:00+00:00,France,1.007853,49.358215
38,FR,SAINT-DIZIER,St DIZIER L. Michel,PM10,eea,µg/m³,15.8,2025-01-31T08:00:00+00:00,France,4.966111,48.645836
39,FR,SAINT-DIZIER,St DIZIER L. Michel,O3,eea,µg/m³,51.9,2025-01-31T08:00:00+00:00,France,4.966111,48.645836
40,FR,CORNEILHAN,Biterrois-Narbonnais,O3,eea,µg/m³,37.3,2025-01-31T08:00:00+00:00,France,3.188780,43.406800
41,FR,CREIL,Faiencerie Creil,PM10,eea,µg/m³,23.4,2025-01-31T08:00:00+00:00,France,2.474397,49.259552
42,FR,VESOUL,Vesoul Pres Caillet,PM10,eea,µg/m³,9.3,2025-01-30T12:00:00+00:00,France,6.157642,47.620020
43,FR,BÉTHUNE,Bethune Stade,NO2,eea,µg/m³,4.0,2025-01-28T02:00:00+00:00,France,2.635692,50.535385
44,FR,BOURGOIN-JALLIEU,Bourgoin-Jallieu,NO2,eea,µg/m³,6.7,2025-01-31T08:00:00+00:00,France,5.270872,45.608220
45,FR,CAEN,Caen Chemin-Vert,PM10,eea,µg/m³,8.7,2025-01-31T08:00:00+00:00,France,-0.391111,49.192220
46,FR,LIEUDIEU,Plateau de Bonnevaux,O3,eea,µg/m³,47.4,2025-01-31T08:00:00+00:00,France,5.181081,45.460900
47,FR,METZ,Metz-Centre,NO2,eea,µg/m³,34.0,2025-01-31T08:00:00+00:00,France,6.180833,49.119442
48,FR,BRUNSTATT-DIDENHEIM,Mulhouse Est,O3,eea,µg/m³,51.0,2025-01-31T08:00:00+00:00,France,7.341603,47.723106
49,FR,PASSY,PASSY,O3,eea,µg/m³,0.4,2025-01-31T07:00:00+00:00,France,6.713611,45.923610

## Q3 : Extraction complète

Maintenant que vous savez récupérer une seule page de données de l'API (Q1) et la transformer en DataFrame (Q2), l'étape suivante consiste à automatiser ce processus pour obtenir *toutes* les données disponibles sur toutes les pages.

Créez une nouvelle fonction qui :

1.  Utilise la fonction `get_content` de manière répétée pour récupérer les données page par page, en ajustant correctement le paramètre `offset`.
2. tilise la fonction `get_dataframe`  pour convertir le json en dataframe

3.  Assemble tous les dataframe  récupérés de chaque page en un seul dataframe


4.  Gère la condition d'arrêt pour savoir quand il n'y a plus de pages à récupérer (l'API OpenDataSoft indique généralement le nombre total d'enregistrements ).

In [24]:
def df_full():
  data_first=api() #stock le resultat de la requete api
  total_count=data_first['total_count'] #stock le nombre de ligne a obtenir pour nous servir a calculer le nombre de page plus tard
  limit=50
  nb_de_page= (total_count//limit)+1
  df_total=pd.DataFrame()
  for i in range (nb_de_page):#le numero de page est ajouter au lien api a chaque tour
    link = 'https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/openaq/records?limit=50&offset='+str(i*50)+'&refine=country_name_en%3A%22France%22&refine=measurements_lastupdated%3A%222025%22&refine=measurements_parameter%3A%22PM10%22&refine=measurements_parameter%3A%22PM2.5%22&refine=measurements_parameter%3A%22O3%22&refine=measurements_parameter%3A%22NO2%22'
    r = requests.get(link) #verifie si acces ok
    if r.status_code == 200:
      data=r.json() #extrait les donnée
      df_page=json_df(data) # on sotcke la page récupéré
      df_total=pd.concat([df_total,df_page]) # on rassemble les page dans le dataframe final
  return df_total

In [25]:
df_full()

,country,city,location,measurements_parameter,measurements_sourcename,measurements_unit,measurements_value,measurements_lastupdated,country_name_en,coordinates.lon,coordinates.lat
0,FR,OUTREAU,Outreau,O3,eea,µg/m³,67.0,2025-01-31T08:00:00+00:00,France,1.576570,50.694350
1,FR,SAINT-LOUIS,Sarda Garriga,NO2,eea,µg/m³,8.6,2025-01-21T06:00:00+00:00,France,55.403065,-21.277075
2,FR,GRANDE-SYNTHE,Grande-synthe,NO2,eea,µg/m³,24.8,2025-01-31T08:00:00+00:00,France,2.302150,51.024460
3,FR,DOLE,Dole centre,O3,eea,µg/m³,56.8,2025-01-31T07:00:00+00:00,France,5.496389,47.096720
4,FR,SAINT-ESTÈVE,Perpignan St Esteve,O3,eea,µg/m³,55.3,2025-01-30T12:00:00+00:00,France,2.839880,42.719800
...,...,...,...,...,...,...,...,...,...,...,...
36,FR,QUIMPER,Quimper Zola,NO2,eea,µg/m³,28.0,2025-01-31T08:00:00+00:00,France,-4.097658,47.986607
37,FR,MONTCEAU-LES-MINES,Montceau-les-Mines 9me écluse,NO2,eea,µg/m³,11.8,2025-01-31T07:00:00+00:00,France,4.366893,46.678783
38,FR,COLMAR,Colmar Centre,NO2,eea,µg/m³,23.7,2025-01-31T08:00:00+00:00,France,7.350555,48.074444
39,FR,GENNEVILLIERS,GENNEVILLIERS,PM10,eea,µg/m³,7.2,2025-01-06T11:00:00+00:00,France,2.294350,48.930320
40,FR,FLOIRAC,Floirac Branne,NO2,eea,µg/m³,38.8,2025-01-31T07:00:00+00:00,France,-0.506980,44.843410

In [27]:
df_total=df_full()

In [30]:
df_total

,country,city,location,measurements_parameter,measurements_sourcename,measurements_unit,measurements_value,measurements_lastupdated,country_name_en,coordinates.lon,coordinates.lat
0,FR,OUTREAU,Outreau,O3,eea,µg/m³,67.0,2025-01-31T08:00:00+00:00,France,1.576570,50.694350
1,FR,SAINT-LOUIS,Sarda Garriga,NO2,eea,µg/m³,8.6,2025-01-21T06:00:00+00:00,France,55.403065,-21.277075
2,FR,GRANDE-SYNTHE,Grande-synthe,NO2,eea,µg/m³,24.8,2025-01-31T08:00:00+00:00,France,2.302150,51.024460
3,FR,DOLE,Dole centre,O3,eea,µg/m³,56.8,2025-01-31T07:00:00+00:00,France,5.496389,47.096720
4,FR,SAINT-ESTÈVE,Perpignan St Esteve,O3,eea,µg/m³,55.3,2025-01-30T12:00:00+00:00,France,2.839880,42.719800
...,...,...,...,...,...,...,...,...,...,...,...
36,FR,QUIMPER,Quimper Zola,NO2,eea,µg/m³,28.0,2025-01-31T08:00:00+00:00,France,-4.097658,47.986607
37,FR,MONTCEAU-LES-MINES,Montceau-les-Mines 9me écluse,NO2,eea,µg/m³,11.8,2025-01-31T07:00:00+00:00,France,4.366893,46.678783
38,FR,COLMAR,Colmar Centre,NO2,eea,µg/m³,23.7,2025-01-31T08:00:00+00:00,France,7.350555,48.074444
39,FR,GENNEVILLIERS,GENNEVILLIERS,PM10,eea,µg/m³,7.2,2025-01-06T11:00:00+00:00,France,2.294350,48.930320
40,FR,FLOIRAC,Floirac Branne,NO2,eea,µg/m³,38.8,2025-01-31T07:00:00+00:00,France,-0.506980,44.843410

## Q4 : Nettoyage du DataFrame

Une fois que vous avez récupéré toutes les données et les avez consolidées dans un DataFrame unique (grâce à Q3), il est temps de nettoyer ce DataFrame pour le rendre plus facile à utiliser pour l'analyse.

Créez une fonction Python qui prend le DataFrame complet en entrée et effectue les opérations suivantes :

-   **Supprimer les colonnes inutiles** : Éliminez les colonnes qui fournissent des informations redondantes pour l'analyse des zones à risque en France, comme :
    -   `location`
    -   `country`
    -   `country_name_en`
    -   `measurements_unit` (l'unité µg/m³ est fixe pour les polluants listés)

-   **Renommer des colonnes** : Donnez des noms plus clairs et uniformes aux colonnes importantes :
    -   `measurements_value` devient `measurements_value(µg/m³)`
    -   `coordinates.lon` devient `longitude`
    -   `coordinates.lat` devient `latitude`

-   **Convertir une colonne en datetime** : Assurez-vous que la colonne `measurements_lastupdated` est bien reconnue comme un type de date et heure par pandas.

-   **Extraire des composants date/heure** : À partir de la colonne `measurements_lastupdated` (une fois convertie), créez de nouvelles colonnes pour extraire des informations temporelles utiles :
    -   La date seule
    -   Le mois (numérique)
    -   L'heure (numérique)
    -   Le jour du mois (numérique)
    -   Le jour de la semaine (mumérique)

-   **Sauvegarder en CSV** : Enfin, sauvegardez ce DataFrame nettoyé dans un fichier CSV (par exemple, `air_quality_cleaned.csv`) pour une utilisation ultérieure, sans inclure l'index du DataFrame.

In [33]:
def cleanning(df):
  df=df.drop(columns=['location','country','country_name_en','measurements_unit'])
  df=df.rename(columns={'measurements_value':'measurements_value(µg/m³)','coordinates.lon':'longitude','coordinates.lat':'latitude'})
  df['measurements_lastupdated']=pd.to_datetime(df['measurements_lastupdated'])
  df['Date']=df['measurements_lastupdated'].dt.date
  df['Mois']=df['measurements_lastupdated'].dt.month
  df['Heure']=df['measurements_lastupdated'].dt.hour
  df['Jour']=df['measurements_lastupdated'].dt.day
  df['jour_semaine']=df['measurements_lastupdated'].dt.dayofweek
  df.to_csv("Dojo_API_Data_Cleaning.csv", index=False)
  return df

In [34]:
cleanning(df_total)

,city,measurements_parameter,measurements_sourcename,measurements_value(µg/m³),measurements_lastupdated,longitude,latitude,Date,Mois,Heure,Jour,jour_semaine
0,OUTREAU,O3,eea,67.0,2025-01-31 08:00:00+00:00,1.576570,50.694350,2025-01-31,1,8,31,4
1,SAINT-LOUIS,NO2,eea,8.6,2025-01-21 06:00:00+00:00,55.403065,-21.277075,2025-01-21,1,6,21,1
2,GRANDE-SYNTHE,NO2,eea,24.8,2025-01-31 08:00:00+00:00,2.302150,51.024460,2025-01-31,1,8,31,4
3,DOLE,O3,eea,56.8,2025-01-31 07:00:00+00:00,5.496389,47.096720,2025-01-31,1,7,31,4
4,SAINT-ESTÈVE,O3,eea,55.3,2025-01-30 12:00:00+00:00,2.839880,42.719800,2025-01-30,1,12,30,3
...,...,...,...,...,...,...,...,...,...,...,...,...
36,QUIMPER,NO2,eea,28.0,2025-01-31 08:00:00+00:00,-4.097658,47.986607,2025-01-31,1,8,31,4
37,MONTCEAU-LES-MINES,NO2,eea,11.8,2025-01-31 07:00:00+00:00,4.366893,46.678783,2025-01-31,1,7,31,4
38,COLMAR,NO2,eea,23.7,2025-01-31 08:00:00+00:00,7.350555,48.074444,2025-01-31,1,8,31,4
39,GENNEVILLIERS,PM10,eea,7.2,2025-01-06 11:00:00+00:00,2.294350,48.930320,2025-01-06,1,11,6,0
40,FLOIRAC,NO2,eea,38.8,2025-01-31 07:00:00+00:00,-0.506980,44.843410,2025-01-31,1,7,31,4