<a href="https://colab.research.google.com/github/chavattecedric-cloud/public/blob/main/C%C3%A9dric_Plotly_Express_Interactive_charts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Execute the code below

In [ ]:
import plotly.express as px
import pandas as pd
import numpy as np
link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/weather2019.csv"
df_weather = pd.read_csv(link)

## You have now a DataFrame with lots of weather data

In [ ]:
df_weather.describe()

,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,PRESSURE_MAX_MB,...,DEWPOINT_MAX_C,WINDTEMP_MAX_C,WEATHER_CODE_MORNING,WEATHER_CODE_NOON,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,MONTH,DAY
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.0,365.000000,365.000000,365.000000,365.000000
mean,16.810959,9.095890,19.624658,10.106849,15.487671,14.958904,3.015890,80.095890,9.428767,1019.038356,...,10.945205,10.989041,168.512329,164.419178,181.638356,0.0,1.380822,9.315890,6.526027,15.720548
std,6.712698,4.814026,8.151987,5.128254,6.565644,6.789290,5.697129,10.413649,2.221039,9.114272,...,4.190159,6.980341,77.739513,78.205120,86.458436,0.0,1.279665,3.608357,3.452584,8.808321
min,5.000000,-1.000000,3.000000,-1.000000,0.000000,0.000000,0.000000,41.000000,5.000000,987.000000,...,1.000000,-4.000000,113.000000,113.000000,113.000000,0.0,1.000000,3.300000,1.000000,1.000000
25%,11.000000,5.000000,14.000000,6.000000,11.000000,10.000000,0.000000,75.000000,8.250000,1014.000000,...,8.000000,5.000000,116.000000,116.000000,116.000000,0.0,1.000000,6.500000,4.000000,8.000000
50%,16.000000,9.000000,18.000000,10.000000,15.000000,14.000000,0.700000,82.000000,9.500000,1020.000000,...,11.000000,10.000000,122.000000,119.000000,122.000000,0.0,1.000000,9.300000,7.000000,16.000000
75%,21.000000,13.000000,25.000000,14.000000,20.000000,19.000000,3.800000,88.000000,10.000000,1024.000000,...,14.000000,17.000000,176.000000,176.000000,176.000000,0.0,1.000000,11.600000,10.000000,23.000000
max,39.000000,25.000000,46.000000,25.000000,36.000000,37.000000,47.600000,98.000000,20.000000,1040.000000,...,25.000000,29.000000,386.000000,353.000000,389.000000,0.0,7.000000,16.000000,12.000000,31.000000

# Now, complete the following tasks :
# Let's go for the show : interactive charts !

## Scatterplot - Add color, title and legend
Need some help ? Go [there for colors](https://plotly.com/python/discrete-color/#directly-mapping-colors-to-data-values) or[ there for labels](https://plotly.com/python/text-and-annotations/)

Maybe [this example](https://plotly.com/python/line-and-scatter/#set-size-and-color-with-column-names) is a good one.

In [ ]:
# Let's draw a simple scatterplot. You know scatterplot, you did a lot with Matplotlib and Seaborn.
# Yes, but here, it's interactive scatterplot.
# Try to draw a rectangle to zoom on the chart, move your mouse over the chart to display values, it's pretty impressive !

fig = px.scatter(data_frame = df_weather, x= "DATE", y="MAX_TEMPERATURE_C",color='OPINION', color_discrete_map={
    'very good': 'green',
    'good': 'lightgreen',
    'not good not bad': 'orange',
    'bad': 'red',
    'very bad': 'darkred'
},title= 'Titre')

fig.show() # This time, it's no more plt.show(), we're well on Plotly

# Now, you have to add different colors by Opinion, add a main center title, axis title,
# and change the color with readable values (green when the opinions are pretty good, et red otherwise)

## Pair Plots

With Plotly, the name of [pairplots](https://plotly.com/python/splom/) is `scatter_matrix`.

In [ ]:
# OK, it's up to you to draw a Pair Plot on the 4 last columns of your DataFrame.
# Do you notice that qualitative values are correctly represented ?
fig = px.scatter_matrix(data_frame = df_weather, dimensions=df_weather.columns[-4:])
fig.show()

## Bubble chart

[Documentation](https://plotly.com/python/bubble-charts/#bubble-chart-with-plotlyexpress)

In [ ]:
# A bubble chart is a scatter plot with different sizes of dots.
# You know how to do scatterplot ? So maybe you can search a "size" argument...
# Now, draw a bubble chart with Date on X-axis, Max Temperature on Y-axis, and Precipitation (rain quantity) for the size.
# Don't forget to add title and axis title.

# which period is the rainiest ?

fig = px.scatter(data_frame = df_weather, x= "DATE", y="MAX_TEMPERATURE_C", size='PRECIP_TOTAL_DAY_MM',title='pluie',labels={'DATE': 'Date', 'MAX_TEMPERATURE_C': 'Température max (°C)'})
fig.show()

## Figure with multi-charts

In [ ]:
# Draw a scatterplot with Max Temperature on Y-axis, and Precipitation on X-axis.
# Not really "one" scatterplot, but 5 charts on columns, one by opinion. Maybe with the "facet_col" argument ?

# Could you add an hover name (when you overview with the mouse) with the Month ?
fig = px.scatter(data_frame = df_weather, x= 'PRECIP_TOTAL_DAY_MM',y= 'MAX_TEMPERATURE_C',facet_col='OPINION',hover_name='MONTH')
fig.show()

## Draw 5 violin charts on the same figure
Do you know box plot ? Violin is like a box plot, but with density.

In [ ]:
# Complete the code below to add Opinion on color argument.
# Change colors to be coherent and not to draw a rainbow.
# Could you read on the graph which is the max temperature for a "bad" weather ? 31

fig = px.violin(df_weather, y="MAX_TEMPERATURE_C",  box=True, points="all",color='OPINION',color_discrete_map={
    'very good': 'green',
    'good': 'lightgreen',
    'not good not bad': 'orange',
    'bad': 'red',
    'very bad': 'darkred'
})
fig.show()

## 3D Chart
Do you have some 3D glasses ?

In [ ]:
# Draw a 3D Scatterplot with Max Temperature on X-axis, Windspeed on Y-axis and Month on Z-axis

fig = px.scatter_3d(df_weather,x= 'MAX_TEMPERATURE_C',y= 'WINDSPEED_MAX_KMH',z='MONTH') #Complete this code
fig.show()

# OK, you can move the cube with your mouse, that's impressive. But it's not readable, let's try another thing with the same data.

## 3D Chart are impressive, but not readable, let's try another thing with the same data.
## Dynamic chart !

Tip : You can force the scale of an axis with update axes. For example, to have a X-axis between 0 and 20, you should use :
`fig.update_xaxes(range=[0, 20])`.
And of course, it's is the same for Y-axis with `update_yaxes`.

In [ ]:
# Draw a scatterplot with Max Temperature on X-axis, Windspeed on Y-axis (same as previously), and Month on animation_frame argument.

fig = px.scatter(df_weather,x='MAX_TEMPERATURE_C',y='WINDSPEED_MAX_KMH',animation_frame='MONTH') #Complete this code
fig.update_xaxes(range=[0, 45])
fig.update_yaxes(range=[0, 50])
fig.show()



# You can push the play button below. That's cool, it's dynamic and readable !
# But... hey ! My dots are going away outside of my chart ! You have to catch them ! (or maybe just change the default value of the scale axis range)

## Another dynamic colored (and more useful) chart
Draw a **barchart** with Day for X-axis and Month for animation.

Choose you prefered variables for Y-axis, and color.

You can use `range_x=[0,31]` to be sure your X-axis will be always the same.

Of course, don't forget to add title, legend, etc...

In [ ]:
df_weather

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,WINDTEMP_MAX_C,WEATHER_CODE_MORNING,WEATHER_CODE_NOON,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,MONTH,DAY
0,2019-01-01,9,4,10,4,7,8,0.2,94,9.000,...,3,116,143,176,0,1,5.1,very bad,1,1
1,2019-01-02,8,5,18,7,7,5,0.0,90,9.000,...,3,119,116,116,0,1,8.7,very bad,1,2
2,2019-01-03,6,0,18,0,4,3,0.0,88,10.000,...,-4,116,116,116,0,1,8.7,very bad,1,3
3,2019-01-04,5,-1,15,-1,4,3,0.0,91,10.000,...,-4,116,116,122,0,1,5.1,very bad,1,4
4,2019-01-05,6,-1,8,-1,4,3,0.0,91,8.000,...,-2,143,116,116,0,1,8.7,very bad,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,13,10,13,10,12,11,0.0,96,7.375,...,8,119,143,116,0,1,8.7,not good not bad,12,27
361,2019-12-28,11,5,12,7,8,8,0.0,93,7.625,...,4,143,116,116,0,1,6.9,very bad,12,28
362,2019-12-29,9,2,11,3,6,7,0.0,86,10.000,...,0,116,116,116,0,1,8.7,very bad,12,29
363,2019-12-30,12,4,7,5,9,9,0.0,61,10.000,...,4,113,113,113,0,1,8.7,very bad,12,30
364,2019-12-31,10,4,13,4,7,9,0.1,94,9.000,...,1,113,143,119,0,1,8.7,very bad,12,31

In [ ]:
# Your code here :
fig = px.bar(df_weather,x='DAY',y='SUNHOUR',animation_frame='MONTH',color='MAX_TEMPERATURE_C')
fig.update_xaxes(range=[0, 31])
fig.update_yaxes(range=[0, 20])
fig.show()

# Export
You just have to execute the code below to download your HTML page. Congratulations ! That's a first step for your data portfolio !

For your information, Plotly export D3.js document embedded in an HTML page. D3.js is JavaScript library. You don't need to know JavaScript to export from Plotly. But, if you are insterested, you [can go here](https://d3js.org/).

In [ ]:
# Export en page web edimensionnabla D3JS
from plotly.offline import plot
plot(fig)

from google.colab import files
files.download('temp-plot.html')